language: cpp

matrix:
  include:
    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Debug
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: COMPILER=g++-4.9 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-4.9
          - g++-4.9

    - os: linux
      env: COMPILER=g++-5 CMAKE_BUILD_TYPE=Release
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update
  - sudo apt-get install qt510-meta-minimal cmake -y

before_script:
  - mkdir build
  - cd build
  - . /opt/qt510/bin/qt510-env.sh
  - CXX=${COMPILER} cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..

script:
- make
